function ARIMA_InfectCluster1Diff2 = modelTimeSeries(S)
% ARIMA_InfectCluster1Diff2 = modelTimeSeries(S)
% returns an estimated model. This code recreates the estimated model
% produced in the Econometric Modeler app. Use the code below to estimate
% the same model, or estimate a model with the same parameters on a new set
% of data.
%
%	Input:
%		S: A table with the same variables as the table imported into the app
%
%	Output:
%		ARIMA_InfectCluster1Diff2: The model containing estimated parameters
%
% Auto-generated by MATLAB Version 9.5 (R2018b) and Econometrics Toolbox Version 5.1 on 24-Jan-2019 10:21:26

InfectCluster1 = S.InfectCluster1;

%% First Order Difference of InfectCluster1
InfectCluster1Diff = [NaN; diff(InfectCluster1)];

%% Estimate an ARIMA Model of time series InfectCluster1Diff
ARIMA_InfectCluster1Diff2 = arima('Constant',NaN,'ARLags',1:2,'D',1,'MALags',1,'Distribution','Gaussian');
ARIMA_InfectCluster1Diff2 = estimate(ARIMA_InfectCluster1Diff2,InfectCluster1Diff,'Display','off');

end