f=figure
%uicontrols can't display latex:
u=uicontrol('units','pixels','position',[20 200 200 24],...
'style','text','string','I can''t display \pi',...
'horiz','left',...
'backgroundcolor',get(f,'color'));

%but text objects can:
axes('units','pixels','position',[20 100 200 24],'visible','off')
text(0,0.5,'I can display $\pi$','interpreter','latex',...
'horiz','left','vert','middle')